// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR_hUEGE1K2QfbCsEH4WiX_qDcZldt1xA',
    appId: '1:537627321444:web:6551084f4140d43fdfab71',
    messagingSenderId: '537627321444',
    projectId: 'wificrack-9be37',
    authDomain: 'wificrack-9be37.firebaseapp.com',
    storageBucket: 'wificrack-9be37.firebasestorage.app',
    measurementId: 'G-9HG2ET4HY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc_LYXgvetiFesQOakvrL2s3dPTfQkd6Y',
    appId: '1:537627321444:android:ed17dc8b4443e057dfab71',
    messagingSenderId: '537627321444',
    projectId: 'wificrack-9be37',
    storageBucket: 'wificrack-9be37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcQr0vQ-dWxptIM90Ar_bHY_YAZWOVaww',
    appId: '1:537627321444:ios:e1330495c096c88bdfab71',
    messagingSenderId: '537627321444',
    projectId: 'wificrack-9be37',
    storageBucket: 'wificrack-9be37.firebasestorage.app',
    iosClientId: '537627321444-gsdi1hi4nsns76jep5g34j949f80i4e4.apps.googleusercontent.com',
    iosBundleId: 'com.wificrack.dz.comwificrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcQr0vQ-dWxptIM90Ar_bHY_YAZWOVaww',
    appId: '1:537627321444:ios:0e7e0f8c666ebfb6dfab71',
    messagingSenderId: '537627321444',
    projectId: 'wificrack-9be37',
    storageBucket: 'wificrack-9be37.firebasestorage.app',
    iosClientId: '537627321444-nted8ndi2dsnps544haseva7l7a4c5gt.apps.googleusercontent.com',
    iosBundleId: 'com.check31.dz.check31',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR_hUEGE1K2QfbCsEH4WiX_qDcZldt1xA',
    appId: '1:537627321444:web:492d5e7fae9b08a0dfab71',
    messagingSenderId: '537627321444',
    projectId: 'wificrack-9be37',
    authDomain: 'wificrack-9be37.firebaseapp.com',
    storageBucket: 'wificrack-9be37.firebasestorage.app',
    measurementId: 'G-GRZL4VJSSV',
  );

}