// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '0-claude/contact.dart';
import '0-claude/conversation.dart';
import '0-claude/message.dart';
import '1-mistral/models/contact.dart';
import '1-mistral/models/message.dart';
import '1-mistral/models/user.dart';
import 'Mistral2laude/contact.dart';
import 'Mistral2laude/message.dart';
import 'Mistral2laude/user.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 1352909896876552310),
    name: 'Contact',
    lastPropertyId: const obx_int.IdUid(28, 9143033824453429950),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3523758842275855329),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7029478441232912359),
        name: 'deviceId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(11, 7928838816390135811),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 664040964344294931),
        name: 'pseudo',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4222088233481002578),
        name: 'addedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(23, 8115997662895880659),
        name: 'avatarPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(24, 4536918078806716725),
        name: 'publicKey',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(25, 1759853076189064763),
        name: 'lastSeen',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(26, 4027806716726179121),
        name: 'isOnline',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(27, 1198295703341997518),
        name: 'deviceModel',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(28, 9143033824453429950),
        name: 'connectionScore',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 42079622743424641),
    name: 'Conversation',
    lastPropertyId: const obx_int.IdUid(10, 4770707650294220423),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7468755314793559821),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5766829068857350625),
        name: 'conversationId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(2, 3531744173449389496),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1804404829155234361),
        name: 'lastMessagePreview',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1452741178874594349),
        name: 'lastMessageTime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4997750064963459974),
        name: 'unreadCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8596695284157800911),
        name: 'isTyping',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3653282430598325292),
        name: 'lastTypingTime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 27871096414500658),
        name: 'isPinned',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6092440692361386422),
        name: 'isArchived',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 4770707650294220423),
        name: 'isMuted',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 5207403318482872241),
    name: 'Message',
    lastPropertyId: const obx_int.IdUid(45, 6607165431970107171),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8324666280496593639),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8837503334982690087),
        name: 'timestamp',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 7395284054603411639),
        name: 'isRead',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(36, 7305513830421097528),
        name: 'messageId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(9, 6426437857068350396),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(37, 8784452192006342902),
        name: 'conversationId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(10, 7439765703523602238),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(38, 6579438558184053491),
        name: 'encryptedContent',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(39, 6508803952963780915),
        name: 'typeIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(40, 2986818561726742471),
        name: 'statusIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(41, 7785675938566242136),
        name: 'isSentByMe',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(42, 3538582569472761408),
        name: 'localMediaPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(43, 4712282084668544063),
        name: 'fileSize',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(44, 6448750486855157335),
        name: 'audioDuration',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(45, 6607165431970107171),
        name: 'sendAttempts',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 3501649989373014041),
    name: 'MistralMessage',
    lastPropertyId: const obx_int.IdUid(9, 5991369762814817482),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3699907472359367942),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 788052598266790922),
        name: 'senderDeviceId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4801961623556548439),
        name: 'receiverDeviceId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8098754433391978216),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7178228122055494950),
        name: 'isVoice',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1293873001414426216),
        name: 'voiceUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7448771927385331261),
        name: 'timestamp',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4272966190525729579),
        name: 'isDelivered',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5991369762814817482),
        name: 'isRead',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 6536817754216737048),
    name: 'MistralContact',
    lastPropertyId: const obx_int.IdUid(4, 3738697608709343080),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2467881686810015133),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4425300105885428014),
        name: 'deviceId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2695757674702586482),
        name: 'pseudo',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3738697608709343080),
        name: 'addedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 6895244940593384499),
    name: 'MistralUser',
    lastPropertyId: const obx_int.IdUid(6, 1048694533670665507),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 677019204230024474),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7840284754299534065),
        name: 'deviceId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1528481963973296190),
        name: 'pseudo',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1869653534986921490),
        name: 'model',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8943710546428408986),
        name: 'lastSeen',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1048694533670665507),
        name: 'coins',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(8, 7712318734714241800),
    name: 'M2CContact',
    lastPropertyId: const obx_int.IdUid(7, 5358493575862507535),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7441680407024736713),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3057196009284395852),
        name: 'deviceId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(12, 1058489827920262486),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6497222624522753489),
        name: 'pseudo',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4754756691977057688),
        name: 'addedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4108046781730202959),
        name: 'lastMessagePreview',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5276665732377637351),
        name: 'lastMessageAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5358493575862507535),
        name: 'unreadCount',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(9, 64266862957739305),
    name: 'M2CMessage',
    lastPropertyId: const obx_int.IdUid(8, 7958303488395925849),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8702605900822452962),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1246683357877766500),
        name: 'senderDeviceId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(13, 2625189339034780444),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1027021775956399174),
        name: 'receiverDeviceId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(14, 5278489592257728386),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 9196075042684398298),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3201417147469289124),
        name: 'isVoice',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2753526326437614394),
        name: 'voiceUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7038187708445271831),
        name: 'timestamp',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7958303488395925849),
        name: 'statusIndex',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(10, 4374981518698559679),
    name: 'M2CUser',
    lastPropertyId: const obx_int.IdUid(6, 5339494152784560966),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4052847937773804465),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4884084724269321527),
        name: 'deviceId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(15, 665958254450218356),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8828332124493694619),
        name: 'pseudo',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6828651518632723847),
        name: 'model',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2271345398154994806),
        name: 'lastSeen',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5339494152784560966),
        name: 'coins',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(10, 4374981518698559679),
    lastIndexId: const obx_int.IdUid(15, 665958254450218356),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [2939193843170496769],
    retiredIndexUids: const [
      2847332930065360165,
      2376645548679472069,
      7681500884766040895,
      5078115415578715721,
      2958933595828251497,
      4998244162498919269,
      4888371701697105827,
    ],
    retiredPropertyUids: const [
      3995661552509416622,
      1873814237312159934,
      3573701226433309399,
      1947913067789202665,
      8198037948888706085,
      464945005527200572,
      4458113978154024013,
      6155820809804168320,
      4509679360986361255,
      5870046853414135668,
      3567161518978684168,
      2528492528009688092,
      1589559501177999440,
      1920795909631557720,
      5888934537576292933,
      8986829967942046750,
      1423015491020647676,
      2152000938663567493,
      5692460287163300095,
      1310797407629302914,
      889627414307795520,
      4343058860373776739,
      725825485958561500,
      2748362937168818669,
      7972011979253124562,
      4863138800462571858,
      1242432179438462551,
      8379131253732908696,
      8866436155652437210,
      3560902985286336648,
      5957285423558007574,
      631589463426943088,
      1586749361915712277,
      4929616419587804903,
      8840361677508854909,
      7866265111417345460,
      4116506327576624814,
      2415352318417309896,
      3156328906387757064,
      4193895451600655387,
      5860277039719432868,
      7613354087610727899,
      1302523714491524378,
      2637158236255333639,
      7844270328176529855,
      6515594422666662254,
      7528998072610784041,
      7260803844531295016,
      5998576096760442579,
      689238461714842244,
      5924645892525882938,
      1135966365786861703,
      399296072509467017,
      7101242708103250279,
      3834670834849857391,
      3024665782778816889,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Contact: obx_int.EntityDefinition<Contact>(
      model: _entities[0],
      toOneRelations: (Contact object) => [],
      toManyRelations: (Contact object) => {},
      getId: (Contact object) => object.id,
      setId: (Contact object, int id) {
        object.id = id;
      },
      objectToFB: (Contact object, fb.Builder fbb) {
        final deviceIdOffset = fbb.writeString(object.deviceId);
        final pseudoOffset = fbb.writeString(object.pseudo);
        final avatarPathOffset = object.avatarPath == null
            ? null
            : fbb.writeString(object.avatarPath!);
        final publicKeyOffset = fbb.writeString(object.publicKey);
        final deviceModelOffset = object.deviceModel == null
            ? null
            : fbb.writeString(object.deviceModel!);
        fbb.startTable(29);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, deviceIdOffset);
        fbb.addOffset(2, pseudoOffset);
        fbb.addInt64(5, object.addedAt.millisecondsSinceEpoch);
        fbb.addOffset(22, avatarPathOffset);
        fbb.addOffset(23, publicKeyOffset);
        fbb.addInt64(24, object.lastSeen?.millisecondsSinceEpoch);
        fbb.addBool(25, object.isOnline);
        fbb.addOffset(26, deviceModelOffset);
        fbb.addInt64(27, object.connectionScore);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final lastSeenValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          52,
        );
        final deviceIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final pseudoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final publicKeyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 50, '');
        final avatarPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 48);
        final addedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final lastSeenParam = lastSeenValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(lastSeenValue);
        final isOnlineParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          54,
          false,
        );
        final deviceModelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 56);
        final connectionScoreParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          58,
          0,
        );
        final object = Contact(
          deviceId: deviceIdParam,
          pseudo: pseudoParam,
          publicKey: publicKeyParam,
          avatarPath: avatarPathParam,
          addedAt: addedAtParam,
          lastSeen: lastSeenParam,
          isOnline: isOnlineParam,
          deviceModel: deviceModelParam,
          connectionScore: connectionScoreParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    Conversation: obx_int.EntityDefinition<Conversation>(
      model: _entities[1],
      toOneRelations: (Conversation object) => [],
      toManyRelations: (Conversation object) => {},
      getId: (Conversation object) => object.id,
      setId: (Conversation object, int id) {
        object.id = id;
      },
      objectToFB: (Conversation object, fb.Builder fbb) {
        final conversationIdOffset = fbb.writeString(object.conversationId);
        final lastMessagePreviewOffset = object.lastMessagePreview == null
            ? null
            : fbb.writeString(object.lastMessagePreview!);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, conversationIdOffset);
        fbb.addOffset(2, lastMessagePreviewOffset);
        fbb.addInt64(3, object.lastMessageTime?.millisecondsSinceEpoch);
        fbb.addInt64(4, object.unreadCount);
        fbb.addBool(5, object.isTyping);
        fbb.addInt64(6, object.lastTypingTime?.millisecondsSinceEpoch);
        fbb.addBool(7, object.isPinned);
        fbb.addBool(8, object.isArchived);
        fbb.addBool(9, object.isMuted);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final lastMessageTimeValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          10,
        );
        final lastTypingTimeValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final conversationIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final lastMessagePreviewParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final lastMessageTimeParam = lastMessageTimeValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(lastMessageTimeValue);
        final unreadCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final isTypingParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          14,
          false,
        );
        final lastTypingTimeParam = lastTypingTimeValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(lastTypingTimeValue);
        final isPinnedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final isArchivedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          20,
          false,
        );
        final isMutedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          22,
          false,
        );
        final object = Conversation(
          conversationId: conversationIdParam,
          lastMessagePreview: lastMessagePreviewParam,
          lastMessageTime: lastMessageTimeParam,
          unreadCount: unreadCountParam,
          isTyping: isTypingParam,
          lastTypingTime: lastTypingTimeParam,
          isPinned: isPinnedParam,
          isArchived: isArchivedParam,
          isMuted: isMutedParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    Message: obx_int.EntityDefinition<Message>(
      model: _entities[2],
      toOneRelations: (Message object) => [],
      toManyRelations: (Message object) => {},
      getId: (Message object) => object.id,
      setId: (Message object, int id) {
        object.id = id;
      },
      objectToFB: (Message object, fb.Builder fbb) {
        final messageIdOffset = fbb.writeString(object.messageId);
        final conversationIdOffset = fbb.writeString(object.conversationId);
        final encryptedContentOffset = fbb.writeString(object.encryptedContent);
        final localMediaPathOffset = object.localMediaPath == null
            ? null
            : fbb.writeString(object.localMediaPath!);
        fbb.startTable(46);
        fbb.addInt64(0, object.id);
        fbb.addInt64(7, object.timestamp.millisecondsSinceEpoch);
        fbb.addBool(11, object.isRead);
        fbb.addOffset(35, messageIdOffset);
        fbb.addOffset(36, conversationIdOffset);
        fbb.addOffset(37, encryptedContentOffset);
        fbb.addInt64(38, object.typeIndex);
        fbb.addInt64(39, object.statusIndex);
        fbb.addBool(40, object.isSentByMe);
        fbb.addOffset(41, localMediaPathOffset);
        fbb.addInt64(42, object.fileSize);
        fbb.addInt64(43, object.audioDuration);
        fbb.addInt64(44, object.sendAttempts);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final messageIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 74, '');
        final conversationIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 76, '');
        final encryptedContentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 78, '');
        final typeIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          80,
          0,
        );
        final statusIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          82,
          0,
        );
        final isSentByMeParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          84,
          false,
        );
        final timestampParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
        );
        final localMediaPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 86);
        final fileSizeParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          88,
        );
        final audioDurationParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          90,
        );
        final isReadParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          26,
          false,
        );
        final sendAttemptsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          92,
          0,
        );
        final object = Message(
          messageId: messageIdParam,
          conversationId: conversationIdParam,
          encryptedContent: encryptedContentParam,
          typeIndex: typeIndexParam,
          statusIndex: statusIndexParam,
          isSentByMe: isSentByMeParam,
          timestamp: timestampParam,
          localMediaPath: localMediaPathParam,
          fileSize: fileSizeParam,
          audioDuration: audioDurationParam,
          isRead: isReadParam,
          sendAttempts: sendAttemptsParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    MistralMessage: obx_int.EntityDefinition<MistralMessage>(
      model: _entities[3],
      toOneRelations: (MistralMessage object) => [],
      toManyRelations: (MistralMessage object) => {},
      getId: (MistralMessage object) => object.id,
      setId: (MistralMessage object, int id) {
        object.id = id;
      },
      objectToFB: (MistralMessage object, fb.Builder fbb) {
        final senderDeviceIdOffset = fbb.writeString(object.senderDeviceId);
        final receiverDeviceIdOffset = fbb.writeString(object.receiverDeviceId);
        final contentOffset = fbb.writeString(object.content);
        final voiceUrlOffset = object.voiceUrl == null
            ? null
            : fbb.writeString(object.voiceUrl!);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, senderDeviceIdOffset);
        fbb.addOffset(2, receiverDeviceIdOffset);
        fbb.addOffset(3, contentOffset);
        fbb.addBool(4, object.isVoice);
        fbb.addOffset(5, voiceUrlOffset);
        fbb.addInt64(6, object.timestamp.millisecondsSinceEpoch);
        fbb.addBool(7, object.isDelivered);
        fbb.addBool(8, object.isRead);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final senderDeviceIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final receiverDeviceIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final isVoiceParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          12,
          false,
        );
        final voiceUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final timestampParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
        );
        final isDeliveredParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final isReadParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          20,
          false,
        );
        final object = MistralMessage(
          senderDeviceId: senderDeviceIdParam,
          receiverDeviceId: receiverDeviceIdParam,
          content: contentParam,
          isVoice: isVoiceParam,
          voiceUrl: voiceUrlParam,
          timestamp: timestampParam,
          isDelivered: isDeliveredParam,
          isRead: isReadParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    MistralContact: obx_int.EntityDefinition<MistralContact>(
      model: _entities[4],
      toOneRelations: (MistralContact object) => [],
      toManyRelations: (MistralContact object) => {},
      getId: (MistralContact object) => object.id,
      setId: (MistralContact object, int id) {
        object.id = id;
      },
      objectToFB: (MistralContact object, fb.Builder fbb) {
        final deviceIdOffset = fbb.writeString(object.deviceId);
        final pseudoOffset = object.pseudo == null
            ? null
            : fbb.writeString(object.pseudo!);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, deviceIdOffset);
        fbb.addOffset(2, pseudoOffset);
        fbb.addInt64(3, object.addedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final deviceIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final pseudoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final addedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final object = MistralContact(
          deviceId: deviceIdParam,
          pseudo: pseudoParam,
          addedAt: addedAtParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    MistralUser: obx_int.EntityDefinition<MistralUser>(
      model: _entities[5],
      toOneRelations: (MistralUser object) => [],
      toManyRelations: (MistralUser object) => {},
      getId: (MistralUser object) => object.id,
      setId: (MistralUser object, int id) {
        object.id = id;
      },
      objectToFB: (MistralUser object, fb.Builder fbb) {
        final deviceIdOffset = fbb.writeString(object.deviceId);
        final pseudoOffset = object.pseudo == null
            ? null
            : fbb.writeString(object.pseudo!);
        final modelOffset = object.model == null
            ? null
            : fbb.writeString(object.model!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, deviceIdOffset);
        fbb.addOffset(2, pseudoOffset);
        fbb.addOffset(3, modelOffset);
        fbb.addInt64(4, object.lastSeen?.millisecondsSinceEpoch);
        fbb.addInt64(5, object.coins);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final lastSeenValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final deviceIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final pseudoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final modelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final lastSeenParam = lastSeenValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(lastSeenValue);
        final coinsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final object = MistralUser(
          deviceId: deviceIdParam,
          pseudo: pseudoParam,
          model: modelParam,
          lastSeen: lastSeenParam,
          coins: coinsParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    M2CContact: obx_int.EntityDefinition<M2CContact>(
      model: _entities[6],
      toOneRelations: (M2CContact object) => [],
      toManyRelations: (M2CContact object) => {},
      getId: (M2CContact object) => object.id,
      setId: (M2CContact object, int id) {
        object.id = id;
      },
      objectToFB: (M2CContact object, fb.Builder fbb) {
        final deviceIdOffset = fbb.writeString(object.deviceId);
        final pseudoOffset = object.pseudo == null
            ? null
            : fbb.writeString(object.pseudo!);
        final lastMessagePreviewOffset = object.lastMessagePreview == null
            ? null
            : fbb.writeString(object.lastMessagePreview!);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, deviceIdOffset);
        fbb.addOffset(2, pseudoOffset);
        fbb.addInt64(3, object.addedAt.millisecondsSinceEpoch);
        fbb.addOffset(4, lastMessagePreviewOffset);
        fbb.addInt64(5, object.lastMessageAt?.millisecondsSinceEpoch);
        fbb.addInt64(6, object.unreadCount);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final lastMessageAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final deviceIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final pseudoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final addedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final lastMessagePreviewParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final lastMessageAtParam = lastMessageAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(lastMessageAtValue);
        final unreadCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final object = M2CContact(
          deviceId: deviceIdParam,
          pseudo: pseudoParam,
          addedAt: addedAtParam,
          lastMessagePreview: lastMessagePreviewParam,
          lastMessageAt: lastMessageAtParam,
          unreadCount: unreadCountParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    M2CMessage: obx_int.EntityDefinition<M2CMessage>(
      model: _entities[7],
      toOneRelations: (M2CMessage object) => [],
      toManyRelations: (M2CMessage object) => {},
      getId: (M2CMessage object) => object.id,
      setId: (M2CMessage object, int id) {
        object.id = id;
      },
      objectToFB: (M2CMessage object, fb.Builder fbb) {
        final senderDeviceIdOffset = fbb.writeString(object.senderDeviceId);
        final receiverDeviceIdOffset = fbb.writeString(object.receiverDeviceId);
        final contentOffset = fbb.writeString(object.content);
        final voiceUrlOffset = object.voiceUrl == null
            ? null
            : fbb.writeString(object.voiceUrl!);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, senderDeviceIdOffset);
        fbb.addOffset(2, receiverDeviceIdOffset);
        fbb.addOffset(3, contentOffset);
        fbb.addBool(4, object.isVoice);
        fbb.addOffset(5, voiceUrlOffset);
        fbb.addInt64(6, object.timestamp.millisecondsSinceEpoch);
        fbb.addInt64(7, object.statusIndex);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final senderDeviceIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final receiverDeviceIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final isVoiceParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          12,
          false,
        );
        final voiceUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final timestampParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
        );
        final object =
            M2CMessage(
                senderDeviceId: senderDeviceIdParam,
                receiverDeviceId: receiverDeviceIdParam,
                content: contentParam,
                isVoice: isVoiceParam,
                voiceUrl: voiceUrlParam,
                timestamp: timestampParam,
              )
              ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
              ..statusIndex = const fb.Int64Reader().vTableGet(
                buffer,
                rootOffset,
                18,
                0,
              );

        return object;
      },
    ),
    M2CUser: obx_int.EntityDefinition<M2CUser>(
      model: _entities[8],
      toOneRelations: (M2CUser object) => [],
      toManyRelations: (M2CUser object) => {},
      getId: (M2CUser object) => object.id,
      setId: (M2CUser object, int id) {
        object.id = id;
      },
      objectToFB: (M2CUser object, fb.Builder fbb) {
        final deviceIdOffset = fbb.writeString(object.deviceId);
        final pseudoOffset = object.pseudo == null
            ? null
            : fbb.writeString(object.pseudo!);
        final modelOffset = object.model == null
            ? null
            : fbb.writeString(object.model!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, deviceIdOffset);
        fbb.addOffset(2, pseudoOffset);
        fbb.addOffset(3, modelOffset);
        fbb.addInt64(4, object.lastSeen?.millisecondsSinceEpoch);
        fbb.addInt64(5, object.coins);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final lastSeenValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final deviceIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final pseudoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final modelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final lastSeenParam = lastSeenValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(lastSeenValue);
        final coinsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final object = M2CUser(
          deviceId: deviceIdParam,
          pseudo: pseudoParam,
          model: modelParam,
          lastSeen: lastSeenParam,
          coins: coinsParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Contact] entity fields to define ObjectBox queries.
class Contact_ {
  /// See [Contact.id].
  static final id = obx.QueryIntegerProperty<Contact>(
    _entities[0].properties[0],
  );

  /// See [Contact.deviceId].
  static final deviceId = obx.QueryStringProperty<Contact>(
    _entities[0].properties[1],
  );

  /// See [Contact.pseudo].
  static final pseudo = obx.QueryStringProperty<Contact>(
    _entities[0].properties[2],
  );

  /// See [Contact.addedAt].
  static final addedAt = obx.QueryDateProperty<Contact>(
    _entities[0].properties[3],
  );

  /// See [Contact.avatarPath].
  static final avatarPath = obx.QueryStringProperty<Contact>(
    _entities[0].properties[4],
  );

  /// See [Contact.publicKey].
  static final publicKey = obx.QueryStringProperty<Contact>(
    _entities[0].properties[5],
  );

  /// See [Contact.lastSeen].
  static final lastSeen = obx.QueryDateProperty<Contact>(
    _entities[0].properties[6],
  );

  /// See [Contact.isOnline].
  static final isOnline = obx.QueryBooleanProperty<Contact>(
    _entities[0].properties[7],
  );

  /// See [Contact.deviceModel].
  static final deviceModel = obx.QueryStringProperty<Contact>(
    _entities[0].properties[8],
  );

  /// See [Contact.connectionScore].
  static final connectionScore = obx.QueryIntegerProperty<Contact>(
    _entities[0].properties[9],
  );
}

/// [Conversation] entity fields to define ObjectBox queries.
class Conversation_ {
  /// See [Conversation.id].
  static final id = obx.QueryIntegerProperty<Conversation>(
    _entities[1].properties[0],
  );

  /// See [Conversation.conversationId].
  static final conversationId = obx.QueryStringProperty<Conversation>(
    _entities[1].properties[1],
  );

  /// See [Conversation.lastMessagePreview].
  static final lastMessagePreview = obx.QueryStringProperty<Conversation>(
    _entities[1].properties[2],
  );

  /// See [Conversation.lastMessageTime].
  static final lastMessageTime = obx.QueryDateProperty<Conversation>(
    _entities[1].properties[3],
  );

  /// See [Conversation.unreadCount].
  static final unreadCount = obx.QueryIntegerProperty<Conversation>(
    _entities[1].properties[4],
  );

  /// See [Conversation.isTyping].
  static final isTyping = obx.QueryBooleanProperty<Conversation>(
    _entities[1].properties[5],
  );

  /// See [Conversation.lastTypingTime].
  static final lastTypingTime = obx.QueryDateProperty<Conversation>(
    _entities[1].properties[6],
  );

  /// See [Conversation.isPinned].
  static final isPinned = obx.QueryBooleanProperty<Conversation>(
    _entities[1].properties[7],
  );

  /// See [Conversation.isArchived].
  static final isArchived = obx.QueryBooleanProperty<Conversation>(
    _entities[1].properties[8],
  );

  /// See [Conversation.isMuted].
  static final isMuted = obx.QueryBooleanProperty<Conversation>(
    _entities[1].properties[9],
  );
}

/// [Message] entity fields to define ObjectBox queries.
class Message_ {
  /// See [Message.id].
  static final id = obx.QueryIntegerProperty<Message>(
    _entities[2].properties[0],
  );

  /// See [Message.timestamp].
  static final timestamp = obx.QueryDateProperty<Message>(
    _entities[2].properties[1],
  );

  /// See [Message.isRead].
  static final isRead = obx.QueryBooleanProperty<Message>(
    _entities[2].properties[2],
  );

  /// See [Message.messageId].
  static final messageId = obx.QueryStringProperty<Message>(
    _entities[2].properties[3],
  );

  /// See [Message.conversationId].
  static final conversationId = obx.QueryStringProperty<Message>(
    _entities[2].properties[4],
  );

  /// See [Message.encryptedContent].
  static final encryptedContent = obx.QueryStringProperty<Message>(
    _entities[2].properties[5],
  );

  /// See [Message.typeIndex].
  static final typeIndex = obx.QueryIntegerProperty<Message>(
    _entities[2].properties[6],
  );

  /// See [Message.statusIndex].
  static final statusIndex = obx.QueryIntegerProperty<Message>(
    _entities[2].properties[7],
  );

  /// See [Message.isSentByMe].
  static final isSentByMe = obx.QueryBooleanProperty<Message>(
    _entities[2].properties[8],
  );

  /// See [Message.localMediaPath].
  static final localMediaPath = obx.QueryStringProperty<Message>(
    _entities[2].properties[9],
  );

  /// See [Message.fileSize].
  static final fileSize = obx.QueryIntegerProperty<Message>(
    _entities[2].properties[10],
  );

  /// See [Message.audioDuration].
  static final audioDuration = obx.QueryIntegerProperty<Message>(
    _entities[2].properties[11],
  );

  /// See [Message.sendAttempts].
  static final sendAttempts = obx.QueryIntegerProperty<Message>(
    _entities[2].properties[12],
  );
}

/// [MistralMessage] entity fields to define ObjectBox queries.
class MistralMessage_ {
  /// See [MistralMessage.id].
  static final id = obx.QueryIntegerProperty<MistralMessage>(
    _entities[3].properties[0],
  );

  /// See [MistralMessage.senderDeviceId].
  static final senderDeviceId = obx.QueryStringProperty<MistralMessage>(
    _entities[3].properties[1],
  );

  /// See [MistralMessage.receiverDeviceId].
  static final receiverDeviceId = obx.QueryStringProperty<MistralMessage>(
    _entities[3].properties[2],
  );

  /// See [MistralMessage.content].
  static final content = obx.QueryStringProperty<MistralMessage>(
    _entities[3].properties[3],
  );

  /// See [MistralMessage.isVoice].
  static final isVoice = obx.QueryBooleanProperty<MistralMessage>(
    _entities[3].properties[4],
  );

  /// See [MistralMessage.voiceUrl].
  static final voiceUrl = obx.QueryStringProperty<MistralMessage>(
    _entities[3].properties[5],
  );

  /// See [MistralMessage.timestamp].
  static final timestamp = obx.QueryDateProperty<MistralMessage>(
    _entities[3].properties[6],
  );

  /// See [MistralMessage.isDelivered].
  static final isDelivered = obx.QueryBooleanProperty<MistralMessage>(
    _entities[3].properties[7],
  );

  /// See [MistralMessage.isRead].
  static final isRead = obx.QueryBooleanProperty<MistralMessage>(
    _entities[3].properties[8],
  );
}

/// [MistralContact] entity fields to define ObjectBox queries.
class MistralContact_ {
  /// See [MistralContact.id].
  static final id = obx.QueryIntegerProperty<MistralContact>(
    _entities[4].properties[0],
  );

  /// See [MistralContact.deviceId].
  static final deviceId = obx.QueryStringProperty<MistralContact>(
    _entities[4].properties[1],
  );

  /// See [MistralContact.pseudo].
  static final pseudo = obx.QueryStringProperty<MistralContact>(
    _entities[4].properties[2],
  );

  /// See [MistralContact.addedAt].
  static final addedAt = obx.QueryDateProperty<MistralContact>(
    _entities[4].properties[3],
  );
}

/// [MistralUser] entity fields to define ObjectBox queries.
class MistralUser_ {
  /// See [MistralUser.id].
  static final id = obx.QueryIntegerProperty<MistralUser>(
    _entities[5].properties[0],
  );

  /// See [MistralUser.deviceId].
  static final deviceId = obx.QueryStringProperty<MistralUser>(
    _entities[5].properties[1],
  );

  /// See [MistralUser.pseudo].
  static final pseudo = obx.QueryStringProperty<MistralUser>(
    _entities[5].properties[2],
  );

  /// See [MistralUser.model].
  static final model = obx.QueryStringProperty<MistralUser>(
    _entities[5].properties[3],
  );

  /// See [MistralUser.lastSeen].
  static final lastSeen = obx.QueryDateProperty<MistralUser>(
    _entities[5].properties[4],
  );

  /// See [MistralUser.coins].
  static final coins = obx.QueryIntegerProperty<MistralUser>(
    _entities[5].properties[5],
  );
}

/// [M2CContact] entity fields to define ObjectBox queries.
class M2CContact_ {
  /// See [M2CContact.id].
  static final id = obx.QueryIntegerProperty<M2CContact>(
    _entities[6].properties[0],
  );

  /// See [M2CContact.deviceId].
  static final deviceId = obx.QueryStringProperty<M2CContact>(
    _entities[6].properties[1],
  );

  /// See [M2CContact.pseudo].
  static final pseudo = obx.QueryStringProperty<M2CContact>(
    _entities[6].properties[2],
  );

  /// See [M2CContact.addedAt].
  static final addedAt = obx.QueryDateProperty<M2CContact>(
    _entities[6].properties[3],
  );

  /// See [M2CContact.lastMessagePreview].
  static final lastMessagePreview = obx.QueryStringProperty<M2CContact>(
    _entities[6].properties[4],
  );

  /// See [M2CContact.lastMessageAt].
  static final lastMessageAt = obx.QueryDateProperty<M2CContact>(
    _entities[6].properties[5],
  );

  /// See [M2CContact.unreadCount].
  static final unreadCount = obx.QueryIntegerProperty<M2CContact>(
    _entities[6].properties[6],
  );
}

/// [M2CMessage] entity fields to define ObjectBox queries.
class M2CMessage_ {
  /// See [M2CMessage.id].
  static final id = obx.QueryIntegerProperty<M2CMessage>(
    _entities[7].properties[0],
  );

  /// See [M2CMessage.senderDeviceId].
  static final senderDeviceId = obx.QueryStringProperty<M2CMessage>(
    _entities[7].properties[1],
  );

  /// See [M2CMessage.receiverDeviceId].
  static final receiverDeviceId = obx.QueryStringProperty<M2CMessage>(
    _entities[7].properties[2],
  );

  /// See [M2CMessage.content].
  static final content = obx.QueryStringProperty<M2CMessage>(
    _entities[7].properties[3],
  );

  /// See [M2CMessage.isVoice].
  static final isVoice = obx.QueryBooleanProperty<M2CMessage>(
    _entities[7].properties[4],
  );

  /// See [M2CMessage.voiceUrl].
  static final voiceUrl = obx.QueryStringProperty<M2CMessage>(
    _entities[7].properties[5],
  );

  /// See [M2CMessage.timestamp].
  static final timestamp = obx.QueryDateProperty<M2CMessage>(
    _entities[7].properties[6],
  );

  /// See [M2CMessage.statusIndex].
  static final statusIndex = obx.QueryIntegerProperty<M2CMessage>(
    _entities[7].properties[7],
  );
}

/// [M2CUser] entity fields to define ObjectBox queries.
class M2CUser_ {
  /// See [M2CUser.id].
  static final id = obx.QueryIntegerProperty<M2CUser>(
    _entities[8].properties[0],
  );

  /// See [M2CUser.deviceId].
  static final deviceId = obx.QueryStringProperty<M2CUser>(
    _entities[8].properties[1],
  );

  /// See [M2CUser.pseudo].
  static final pseudo = obx.QueryStringProperty<M2CUser>(
    _entities[8].properties[2],
  );

  /// See [M2CUser.model].
  static final model = obx.QueryStringProperty<M2CUser>(
    _entities[8].properties[3],
  );

  /// See [M2CUser.lastSeen].
  static final lastSeen = obx.QueryDateProperty<M2CUser>(
    _entities[8].properties[4],
  );

  /// See [M2CUser.coins].
  static final coins = obx.QueryIntegerProperty<M2CUser>(
    _entities[8].properties[5],
  );
}
